## Investigating Child Undernutrition Rates in Haiti Post-Earthquake with Geospatial Data Methods

#### Brianna Williams

#### 27 April 2020

**Abstract:**	

Nutrition is a quintessential sustainable development goal. Child malnutrition can be a cause of long-term effects such as inadequate dietary intake and diseases, as well as short term effects like natural disasters and political turmoil. In 2010, a 7.0 magnitude earthquake struck Haiti and devastated millions. As an immediate effect of this natural disaster, child malnutrition became a relevant developmental issue in Haiti. The disaster substantially impacted sectoral conditions such as drinking water, sanitation, energy/fuel, food supply, healthcare, and clearing of debris by the disaster. Hence, these conditions note to have a disruption on the direct development of Haiti and stunted the process. When considering solutions, humanitarian aid narrowed in on improving these sectoral and household conditions to lessen the rate. To accurately distribute resources and further understand how rates are changing, various geospatial data methods investigating the impact natural disasters have on nutrition rates were analyzed and compared, including: DHS data, spatial video, geographically weighted regression (GWR), and ordinary least squares regression models (OLS). These methods concluded that immediately, humanitarian aid improved the rates; however, rates declined again nearly 4 months after the disaster. Additionally, they investigated other outside conditions that initially improved the nutrition rate. The central research question being investigated inquires which data collecting method accurately depicts the change in rates following the 2010 earthquake. There is lack of research regarding how the earthquake specific humanitarian aid altered these rates, especially since there was a severe cholera outbreak around the same time. Improving the verifiability of the survey data and identifying specific sectoral conditions can help target patterns in children who suffer from undernutrition. 
